project_id = "tjagvgqthlibdpvztvaf"

[functions.r2-storage]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.generate-export]
verify_jwt = false

[functions.create-user]
verify_jwt = false
